name: Merge release into stable branch

on:
  release:
    types:
      - published

jobs:
  merge-to-stable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge release into stable branch
        run: |
          git fetch origin
          git checkout stable
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git rebase ${{ github.ref }}
      # https://github.com/marketplace/actions/github-push
      - name: Push changes
        uses: ad-m/github-push-action@0fafdd62b84042d49ec0cb92d9cac7f7ce4ec79e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: stable
